name: Stats Update
on:
  schedule:
    - cron: "5 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Stats Update
        uses: amistaa/amista-uwu@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 048a53d5d4c2780daf2e9a4f30ab7148
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
